import RPi.GPIO as GPIO
from gpiozero import LED
import time

GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)

GPIO.setup(2, GPIO.OUT)
GPIO.setup(3, GPIO.OUT)
GPIO.setup(4, GPIO.OUT)
GPIO.setup(14, GPIO.OUT)

GPIO.setup(17, GPIO.IN)
GPIO.setup(27, GPIO.IN)
GPIO.setup(22, GPIO.IN)
GPIO.setup(23, GPIO.IN)

a = LED(20)
b = LED(16)
c = LED(21)
d = LED(5)
e = LED(6)
f = LED(13)
g = LED(19)
dp = LED(26)

def keypad():
    GPIO.output(2, True)
    if GPIO.input(17) == 1:
        b.on()
        c.on()
        time.sleep(1)
        c.off()
        b.off()
    if GPIO.input(27) == 1:
        a.on()
        b.on()
        g.on()
        e.on()
        d.on()
        time.sleep(1)
        d.off()
        e.off()
        g.off()
        b.off()
        a.off()
    if GPIO.input(22) == 1:
        a.on()
        b.on()
        g.on()
        c.on()
        d.on()
        time.sleep(1)
        d.off()
        c.off()
        g.off()
        b.off()
        a.off()
    if GPIO.input(23) == 1:
        e.on()
        f.on()
        a.on()
        b.on()
        c.on()
        g.on()
        time.sleep(1)
        g.off()
        c.off()
        b.off()
        a.off()
        f.off()
        e.off()
    GPIO.output(2, False)
        
    GPIO.output(3, True)
    if GPIO.input(17) == 1:
        f.on()
        g.on()
        b.on()
        c.on()
        time.sleep(1)
        c.off()
        b.off()
        g.off()
        f.off()
    if GPIO.input(27) == 1:
        a.on()
        f.on()
        g.on()
        c.on()
        d.on()
        time.sleep(1)
        d.off()
        c.off()
        g.off()
        f.off()
        a.off()
    if GPIO.input(22) == 1:
        a.on()
        f.on()
        e.on()
        d.on()
        c.on()
        g.on()
        time.sleep(1)
        g.off()
        c.off()
        d.off()
        e.off()
        f.off()
        a.off()
    if GPIO.input(23) == 1:
        f.on()
        e.on()
        d.on()
        c.on()
        g.on()
        time.sleep(1)
        g.off()
        c.off()
        d.off()
        e.off()
        f.off()
    GPIO.output(3, False)
        
    GPIO.output(4, True)
    if GPIO.input(17) == 1:
        a.on()
        b.on()
        c.on()
        time.sleep(1)
        c.off()
        b.off()
        a.off()
    if GPIO.input(27) == 1:
        a.on()
        b.on()
        g.on()
        e.on()
        d.on()
        c.on()
        f.on()
        time.sleep(1)
        f.off()
        c.off()
        d.off()
        e.off()
        g.off()
        b.off()
        a.off()
    if GPIO.input(22) == 1:
        g.on()
        f.on()
        a.on()
        b.on()
        c.on()
        d.on()
        time.sleep(1)
        d.off()
        c.off()
        b.off()
        a.off()
        f.off()
        g.off()
    if GPIO.input(23) == 1:
        a.on()
        f.on()
        e.on()
        d.on()
        time.sleep(1)
        d.off()
        e.off()
        f.off()
        a.off()
    GPIO.output(4, False)
        
    GPIO.output(14, True)
    if GPIO.input(17) == 1:
        print("Asterisk not available")
    if GPIO.input(27) == 1:
        a.on()
        b.on()
        c.on()
        d.on()
        e.on()
        f.on()
        time.sleep(1)
        f.off()
        e.off()
        d.off()
        c.off()
        b.off()
        a.off()
    if GPIO.input(22) == 1:
        print("Hashtag not available")
    if GPIO.input(23) == 1:
        b.on()
        c.on()
        d.on()
        e.on()
        g.on()
        time.sleep(1)
        g.off()
        e.off()
        d.off()
        c.off()
        b.off()
    GPIO.output(14, False)
        
    return

while True:
    time.sleep(0.1)
    keypad()
