from gpiozero import LED
import time

a = LED(2)
b = LED(3)
c = LED(4)
d = LED(17)
e = LED(27)
f = LED(22)
g = LED(10)
dp = LED(9)

print("What hexadecimal number do you want displayed?")
i = input("1. 1 \n2. 2 \n3. 3 \n4. 4 \n5. 5 \n6. 6 \n7. 7 \n8. 8 \n9. 9\n10. 0 \n11. A \n12. B \n13. C \n14. D \n15. E \n16. F \n17. Exit \n")

while i != "17":
    if i == "1":
        print("1")
        b.on()
        c.on()
        time.sleep(2.5)
        b.off()
        c.off()

    if i =="2":
        print("2")
        a.on()
        b.on()
        g.on()
        e.on()
        d.on()
        time.sleep(2.5)
        a.off()
        g.off()
        g.off()
        e.off()
        d.off()
        
    if i == "3":
        print("3")
        a.on()
        b.on()
        g.on()
        c.on()
        d.on()
        time.sleep(1)
        a.off()
        b.off()
        g.off()
        c.off()
        d.off()
        
    if i == "4":
        print("4")
        f.on()
        g.on()
        b.on()
        c.on()
        time.sleep(1)
        f.off()
        g.off()
        b.off()
        c.off()

    if i == "5":
        print("5")
        a.on()
        f.on()
        g.on()
        d.on()
        c.on()
        time.sleep(1)
        a.off()
        f.off()
        g.off()
        d.off()
        c.off()

    if i == "6":
        print("6")
        a.on()
        f.on()
        e.on()
        d.on()
        c.on()
        g.on()
        time.sleep(1)
        a.off()
        f.off()
        e.off()
        d.off()
        c.off()
        g.off()

    if i == "7":
        print("7")
        a.on()
        b.on()
        c.on()
        time.sleep(1)
        a.off()
        b.off()
        c.off()

    if i == "8":
        print("8")
        a.on()
        f.on()
        g.on()
        c.on()
        d.on()
        e.on()
        b.on()
        time.sleep(1)
        a.off()
        f.off()
        g.off()
        c.off()
        d.off()
        e.off()
        b.off()

    if i == "9":
        print("9")
        a.on()
        f.on()
        g.on()
        b.on()
        c.on()
        d.on()
        time.sleep(1)
        a.off()
        f.off()
        g.off()
        b.off()
        c.off()
        d.off()
    
    if i == "10":
        print("0")
        f.on()
        e.on()
        d.on()
        c.on()
        b.on()
        a.on()
        time.sleep(1)
        f.off()
        e.off()
        d.off()
        c.off()
        b.off()
        a.off()

    if i == "11":
        print("A")
        e.on()
        f.on()
        a.on()
        b.on()
        c.on()
        g.on()
        time.sleep(1)
        e.off()
        f.off()
        a.off()
        b.off()
        c.off()
        g.off()

    if i == "12":
        print("b")
        f.on()
        e.on()
        d.on()
        c.on()
        g.on()
        time.sleep(1)
        f.off()
        e.off()
        d.off()
        c.off()
        g.off()

    if i == "13":
        print("C")
        a.on()
        f.on()
        e.on()
        d.on()
        time.sleep(1)
        a.off()
        f.off()
        e.off()
        d.off()

    if i == "14":
        print("d")
        b.on()
        c.on()
        d.on()
        e.on()
        g.on()
        time.sleep(1)
        b.off()
        c.off()
        d.off()
        e.off()
        g.off()

    if i == "15":
        print("E")
        a.on()
        f.on()
        g.on()
        e.on()
        d.on()
        time.sleep(1)
        a.off()
        f.off()
        g.off()
        e.off()
        d.off()

    if i == "16":
        print("F")
        a.on()
        f.on()
        g.on()
        e.on()
        time.sleep(1)
        a.off()
        f.off()
        g.off()
        e.off
        
    print("What hexadecimal number do you want displayed?")
    i = input("1. 1 \n2. 2 \n3. 3 \n4. 4 \n5. 5 \n6. 6 \n7. 7 \n8. 8 \n9. 9\n10. 0 \n11. A \n12. B \n13. C \n14. D \n15. E \n16. F \n17. Exit \n")
