import RPi.GPIO as GPIO
import time

def segment():
    GPIO.setwarnings(False)    
    GPIO.setmode(GPIO.BCM)
    GPIO.setup(2, GPIO.OUT)
    GPIO.setup(3, GPIO.IN)
    GPIO.setup(21, GPIO.OUT)
    GPIO.setup(20, GPIO.OUT)
    GPIO.setup(26, GPIO.OUT)
    GPIO.setup(19, GPIO.OUT)
    GPIO.setup(13, GPIO.OUT)
    GPIO.setup(6, GPIO.OUT)
    GPIO.setup(5, GPIO.OUT)
    GPIO.setup(0, GPIO.OUT)
    GPIO.setup(1, GPIO.OUT)
    GPIO.setup(7, GPIO.OUT)
    GPIO.setup(8, GPIO.OUT)
    GPIO.setup(25, GPIO.OUT)
    time.sleep(1)
    GPIO.output(21, False)
    GPIO.output(20, False)
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    GPIO.output(0, False)
    
    GPIO.output(1, True)
    GPIO.output(7, True)
    GPIO.output(8, True)
    GPIO.output(25, True)
    GPIO.output(21, False)
    GPIO.output(20, False)
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    GPIO.output(0, False)


    GPIO.output(1, False)
    GPIO.output(21, True)
    time.sleep(1)
    GPIO.output(20, True)
    time.sleep(1)
    GPIO.output(26, True)
    time.sleep(1)
    GPIO.output(19, True)
    time.sleep(1)
    GPIO.output(13, True)
    time.sleep(1)
    GPIO.output(6, True)
    time.sleep(1)
    GPIO.output(5, True)
    time.sleep(1)
    GPIO.output(0, True)
    time.sleep(1)
    GPIO.output(1, True)
    GPIO.output(21, False)
    GPIO.output(20, False)
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    GPIO.output(0, False)
    
    GPIO.output(7, False)
    GPIO.output(21, True)
    time.sleep(1)
    GPIO.output(20, True)
    time.sleep(1)
    GPIO.output(26, True)
    time.sleep(1)
    GPIO.output(19, True)
    time.sleep(1)
    GPIO.output(13, True)
    time.sleep(1)
    GPIO.output(6, True)
    time.sleep(1)
    GPIO.output(5, True)
    time.sleep(1)
    GPIO.output(0, True)
    time.sleep(1)
    GPIO.output(7, True)
    GPIO.output(21, False)
    GPIO.output(20, False)
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    GPIO.output(0, False)
    
    GPIO.output(8, False)
    GPIO.output(21, True)
    time.sleep(1)
    GPIO.output(20, True)
    time.sleep(1)
    GPIO.output(26, True)
    time.sleep(1)
    GPIO.output(19, True)
    time.sleep(1)
    GPIO.output(13, True)
    time.sleep(1)
    GPIO.output(6, True)
    time.sleep(1)
    GPIO.output(5, True)
    time.sleep(1)
    GPIO.output(0, True)
    time.sleep(1)
    GPIO.output(8, True)
    GPIO.output(21, False)
    GPIO.output(20, False)
    GPIO.output(26, False)
    GPIO.output(19, False)
    GPIO.output(13, False)
    GPIO.output(6, False)
    GPIO.output(5, False)
    GPIO.output(0, False)
    
    GPIO.output(19, True)
    GPIO.output(1, False)
    time.sleep(1)
    GPIO.output(1, True)
    GPIO.output(7, False)
    time.sleep(1)
    GPIO.output(7, True)
    GPIO.output(8, False)
    time.sleep(1)
    GPIO.output(8, True)
    
    return

try:
    while True:
        segment()
except KeyboardInterrupt:
	GPIO.cleanup()
